### PR TITLE
Remove domain from esx name

### PR DESCRIPTION
**Pull request by MicKBfr**
Domain in esx name can be a problem with influxgraph and grafana.

### CODE REVIEW

**Comment by sofixa** [comment]
Hi, @MicKBfr . This would be a breaking change and can make for some weirdness, so could you please make it optional (with a flag in the config file, like the one for domain)? 

Adrian

**Comment by MicKBfr** [comment]
OK, i will try to make it optional.
Any idea for flag name ? RemoveDomainHostName ?
Thanks

**Comment by sofixa** [comment]
@MicKBfr i think something more like RemoveDomainFromHostName or RemoveHostDomainName , however unappealing, might be more obvious.

Adrian

**Comment by MicKBfr** [comment]
Hi Adrian,
I have made some change to make it optional, but i'm not a good dev...
I have  compilation problem from my docker with master version. I have already made container previously without problem

> Step 3 : RUN go get -u github.com/vmware/govmomi &&     go get -u github.com/influxdata/influxdb/client/v2 &&   go get  github.com/Oxalide/vsphere-influxdb-go
>  
> # github.com/Oxalide/vsphere-influxdb-go
> src/github.com/Oxalide/vsphere-influxdb-go/vsphere-influxdb.go:473: device.Backing undefined (type types.BaseVirtualDevice has no field or method Backing)
> src/github.com/Oxalide/vsphere-influxdb-go/vsphere-influxdb.go:477: device.diskObjectId undefined (type types.BaseVirtualDevice has no field or method diskObjectId)
> src/github.com/Oxalide/vsphere-influxdb-go/vsphere-influxdb.go:477: device.Backing undefined (type types.BaseVirtualDevice has no field or method Backing)
> The command '/bin/sh -c go get -u github.com/vmware/govmomi &&  go get -u github.com/influxdata/influxdb/client/v2 &&   go get  github.com/Oxalide/vsphere-influxdb-go' returned a non-zero code: 2
> 

Have you a  idea?
Thanks
Mickael

**Comment by sofixa** [comment]
@MicKBfr yeah, sorry about that, master is currently broken (hadn't had the time to fix it yet), you should build with the latest stable tag.

Adrian

**Comment by jorioux** [comment]
@sofixa I would really appreciate if you could merge this pull into master and build the rpm. The last binaries are quite old.

**Pull request merged**
