### PR TITLE
Nested Folders and measurement prefix support

### PR DESCRIPTION
**Pull request by artashus**
The tool was not able to gather info from the datacenters in nested folders under the root folder - fixed, added config parameter to specify prefix for measurement, cleaned up logging formatting

### CODE REVIEW

**Comment by sofixa** [comment]
Hi, thanks a lot for your PR! Could you just run go fmt on your code and re-commit , because now the diff is huge and unhelpful due to a change in indentation?

Adtian

**Comment by artashus** [comment]
Hi, done. i somehow overwritten your .gitignore :( restored it

**Comment by sofixa** [comment]
Thanks! I'll just add a default value in the configuration struct for the prefix(in order not to break existing configurations when people update).

**Comment by sofixa** [comment]
Again, thanks a lot! Released as [0.8.4](https://github.com/Oxalide/vsphere-influxdb-go/releases/tag/v0.8.4).

**Pull request merged**
